export default {
"login": "juanmagal10",
  "id": 91737946,
  "node_id": "U_kgDOBXfPWg",
  "avatar_url": "https://avatars.githubusercontent.com/u/91737946?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/juanmagal10",
  "html_url": "https://github.com/juanmagal10",
  "followers_url": "https://api.github.com/users/juanmagal10/followers",
  "following_url": "https://api.github.com/users/juanmagal10/following{/other_user}",
  "gists_url": "https://api.github.com/users/juanmagal10/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/juanmagal10/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/juanmagal10/subscriptions",
  "organizations_url": "https://api.github.com/users/juanmagal10/orgs",
  "repos_url": "https://api.github.com/users/juanmagal10/repos",
  "events_url": "https://api.github.com/users/juanmagal10/events{/privacy}",
  "received_events_url": "https://api.github.com/users/juanmagal10/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Juan Manuel Galván",
  "company": null,
  "blog": "jmg-portfolio.vercel.app/",
  "location": "Cordoba, Argentina",
  "email": null,
  "hireable": null,
  "bio": null,
  "twitter_username": null,
  "public_repos": 34,
  "public_gists": 0,
  "followers": 3,
  "following": 4,
  "created_at": "2021-10-01T12:49:12Z",
  "updated_at": "2022-07-26T21:13:58Z"
};
